import sys
from api.usajobs import fetch_jobs
from crew.job_crew import run_job_crew

SAMPLE_RESUME = """
TEST USER
Remote | testuser@email.com | linkedin.com/in/testuser | (555) 123-4567

PROFESSIONAL SUMMARY
Results-driven Data Analyst with 4+ years of experience in data visualization, statistical analysis, and database management. Proven ability to translate complex datasets into actionable business insights that drive revenue growth and operational efficiency.

EXPERIENCE
Data Analyst | Tech Solutions Inc. | Jan 2021 - Present
- Designed and maintained automated interactive dashboards using Tableau, reducing weekly reporting time by 15 hours.
- Analyzed customer churn data using Python and SQL, identifying key attrition factors and helping implement a retention strategy that reduced churn by 12%.
- Collaborated with cross-functional teams to define KPIs and build data pipelines.

Junior Data Analyst | Retail Analytics Corp | Jun 2018 - Dec 2020
- Cleaned and processed large retail datasets containing millions of rows using Pandas and SQL.
- Created weekly sales reports for executive leadership.
- Assisted in A/B testing analysis for e-commerce website improvements, contributing to a 5% increase in conversion rate.

EDUCATION
Bachelor of Science in Computer Science
University of Technology, 2018

SKILLS
Programming: Python (Pandas, NumPy), SQL, R
Data Visualization: Tableau, PowerBI, Matplotlib
Tools & Platforms: Excel (Advanced), Git, Jupyter, AWS
"""

if __name__ == "__main__":
    print("="*70)
    print("🚀 MULTI-AGENT JOB SEARCH SYSTEM - PIPELINE TEST 🚀")
    print("="*70)
    
    print("\n[1] Fetching jobs from USAJOBS API...")
    print("    Keyword: 'Data Analyst' | Location: 'Remote'")
    
    jobs = fetch_jobs(keyword="Data Analyst", location="Remote", results_per_page=5)
    
    if not jobs:
        print("\n❌ No jobs found or there was an error fetching from USAJOBS.")
        print("    Ensure your .env file has valid USAJOBS_API_KEY and USAJOBS_USER_AGENT.")
        sys.exit(1)
        
    # Take the first job from the results
    target_job = jobs[0]
    job_title = target_job['title']
    organization = target_job['organization']
    job_description = target_job['description']
    
    print(f"\n✅ Successfully fetched {len(jobs)} jobs.")
    print(f"🎯 Target Job Selected:")
    print(f"   Title: {job_title}")
    print(f"   Org:   {organization}")
    print("-" * 70)
    
    print("\n[2] Initializing CrewAI multi-agent pipeline...")
    
    # Run the multi-agent crew using the target job and sample resume
    results = run_job_crew(
        job_description=job_description,
        original_resume=SAMPLE_RESUME,
        job_title=job_title,
        company=organization,
        candidate_name="Test User"
    )
    
    print("\n" + "="*70)
    print("🏆 FINAL OUTPUT: RESUME & COVER LETTER 🏆")
    print("="*70 + "\n")
    
    # Print exactly the target resume and cover letter result generated by the agents
    print(results.get("resume_and_cover_letter", "No resume output generated."))
    
    print("\n" + "="*70)
    print("🏁 PIPELINE TEST COMPLETE 🏁")
    print("="*70)
